// containing all actions
export default {
  GET_WELCOME: 'GET_WELCOME',
  REGISTER: 'REGISTER',
  READ_ARTICLE_ERROR: 'READ_ARTICLE_ERROR',
  SEND_RESET_PASSWORD_EMAIL: 'SEND_RESET_PASSWORD_EMAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  FETCH_TERMS: 'FETCH_TERMS',
  GET_CATEGORIES: 'GET_CATEGORIES',
  CREATE_ARTICLE: 'CREATE_ARTICLE',
  CREATE_ARTICLE_ERROR: 'CREATE_ARTICLE_ERROR',
  CHANGE_STATE: 'CHANGE_STATE',
  GET_TAGS: 'GET_TAGS',
  AUTO_SAVE: 'AUTO_SAVE',
  PUBLISH_ARTICLE: 'PUBLISH_ARTICLE',
  FETCH_ONE_ARTICLE: 'FETCH_ONE_ARTICLE',
  GET_ARTICLE_TAGS: 'GET_ARTICLE_TAGS',
  GET_POPULAR_ARTICLES: 'GET_POPULAR_ARTICLES',
  CATCH_ERROR: 'CATCH_ERROR'
};
