// containing all actions
export default {
  GET_WELCOME: 'GET_WELCOME',
  REGISTER: 'REGISTER',
  CATCH_ERROR: 'CATCH_ERROR',
  SEND_RESET_PASSWORD_EMAIL: 'SEND_RESET_PASSWORD_EMAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  SHOW_NOTIFICATIONS: 'SHOW_NOTIFICATIONS',
  HIDE_NOTIFICATIONS: 'HIDE_NOTIFICATIONS',
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  NOTIFICATIONS_CATCH_ERROR: 'NOTIFICATIONS_CATCH_ERROR',
  SNOOZE_NOTIFICATION: 'SNOOZE_NOTIFICATION',
  GET_NOTIFICATIONS_CONFIGS: 'GET_NOTIFICATIONS_CONFIGS',
  GET_USER_PROFILE_ON_LOGIN: 'GET_USER_PROFILE_ON_LOGIN',
  MARK_NOTIFICATION_AS_READ: 'MARK_NOTIFICATION_AS_READ',
  MARK_ALL_NOTIFICATIONS_AS_READ: 'MARK_ALL_NOTIFICATIONS_AS_READ',
  GET_IO_NOTIFICATION: 'GET_IO_NOTIFICATION'
};
